### ISSUE TITLE
build.sh fails

### ISSUE THREAD

**Issue by Rubyfi** [FTSRG/ttc16-cra-viatra-dse#2]
Hey there,

I'm trying to build your solution using `build.sh` on the latest version of OS X, but I'm getting the following error:

```
[ERROR] Failed to resolve target definition /Users/user/git/ttc16/ttc16-cra-viatra-dse/hu.bme.mit.viatra.ttc.target/hu.bme.mit.viatra.ttc.target.target: Could not find "org.eclipse.viatra.dse.api/0.13.0.201605201634" in the repositories of the current location -> [Help 1]
```

Do you know what might cause this or give me some directions on how to resolve it?

Best regards,
Stefan

**Comment by szarnyasg** [comment]
@Rubyfi hey, it's now fixed! Thanks for reporting.
